  version: "3.3"
  services:
    webcontainer:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          GITHUB_TOKEN: ${BUILD_GITHUB_TOKEN}
      ports:
        - "8000:8080"
      networks:
        - localnet
  networks:
    localnet:
